// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtiSB6ROoFg0wM-eEOQMTj18_hArfvjDk',
    appId: '1:485165006027:android:00f195d975001ec65eef4e',
    messagingSenderId: '485165006027',
    projectId: 'gymix-8fc00',
    databaseURL: 'https://gymix-8fc00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymix-8fc00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-3Xbrc09SAhBD4Crzz-RDH_9-0Y0OAM',
    appId: '1:485165006027:ios:535d849db888a04c5eef4e',
    messagingSenderId: '485165006027',
    projectId: 'gymix-8fc00',
    databaseURL: 'https://gymix-8fc00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymix-8fc00.appspot.com',
    iosClientId: '485165006027-r9oefc2qlgmdpm0scuu7s2llp82cqjs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymix',
  );
}
